Update xtreammaker.yml

diff --git a/.github/workflows/xtreammaker.yml b/.github/workflows/xtreammaker.yml
--- a/.github/workflows/xtreammaker.yml
+++ b/.github/workflows/xtreammaker.yml
@@ -236,13 +236,8 @@ jobs:
 
       - name: Xtream Cache Clear
         run: |
-         echo "🚀 Clearing Xtream cache..."
-
-         for i in {1..6}; do
-           echo "🔁 Cache clear attempt $i/6"
-           curl -X GET "$XTREAM_CACHE_URL" || echo "⚠️ Cache clear request failed"
-           sleep 5
-         done
+          echo "🚀 Clearing Xtream cache..."
+          curl -X GET "$XTREAM_CACHE_URL" || echo "⚠️ Cache clear request failed"
          
       - name: Telegram Success Notification
         if: success()
